
/*******************************************************************************
Copyright (C) 2014, 2015, Marvell International Ltd. and its affiliates
If you received this File from Marvell and you have entered into a commercial
license aGLBLeement (a "Commercial License") with Marvell, the File is licensed
to you under the terms of the applicable Commercial License.
*******************************************************************************/

/********************************************************************
This file contains redefined names of all global functions and variables
used by MCD library. Renaming used to avoid link level conflict with another instance of
MCD library (typicaly another version dedicated for another PHY).
Names defined in firmware and in sample sources not included to this file.
********************************************************************/
#ifndef MCD_API_HIDDEN_NAMES_H
#define MCD_API_HIDDEN_NAMES_H
#if C_LINKAGE
#if defined __cplusplus
    extern "C" {
#endif
#endif

    /* names retrieved from cpssEnabler.map file */
    /* expanded by prefix phy5123_               */

/* src/mcdApi.o */

#define mcdSampleInitDrv         phy5123_mcdSampleInitDrv
#define mcdSampleUnloadDrv       phy5123_mcdSampleUnloadDrv
#define mcdSampleSetMode         phy5123_mcdSampleSetMode


#define mcdSyncEClkConfig						phy5123_mcdSyncEClkConfig
#define mcdSetModeSelectionLaneSteering         phy5123_mcdSetModeSelectionLaneSteering
#define mcdSet100GLaneSteering					phy5123_mcdSet100GLaneSteering
#define mcdSet40GLaneSteering					phy5123_mcdSet40GLaneSteering
#define mcdSetLaneSteering						phy5123_mcdSetLaneSteering
#define mcdPortStop                             phy5123_mcdPortStop
#define mcdSetAPModeSelection                   phy5123_mcdSetAPModeSelection
#define mcdSetModeSelectionExt                  phy5123_mcdSetModeSelectionExt
#define mcdSetModeSelection                     phy5123_mcdSetModeSelection
#define mcdSetAutoNegAdvertisingSpeeds          phy5123_mcdSetAutoNegAdvertisingSpeeds
#define mcdGetAutoNegAdvertisingSpeeds          phy5123_mcdGetAutoNegAdvertisingSpeeds
#define mcdGetAutoNegParameters                 phy5123_mcdGetAutoNegParameters
#define mcdSquelchRxClockSet                    phy5123_mcdSquelchRxClockSet
#define mcdAutoNegStart                         phy5123_mcdAutoNegStart
#define mcdAutoNegDisable                       phy5123_mcdAutoNegDisable
#define mcdAutoNegEnable                        phy5123_mcdAutoNegEnable
#define mcdAutoNegCheckCompleteExt              phy5123_mcdAutoNegCheckCompleteExt
#define mcdAutoNegCheckComplete                 phy5123_mcdAutoNegCheckComplete
#define mcdCheckLinkStatus                      phy5123_mcdCheckLinkStatus
#define mcdGetPcsFaultStatus                    phy5123_mcdGetPcsFaultStatus
#define mcdGetCm3ToHostSignal                   phy5123_mcdGetCm3ToHostSignal
#define mcdSetInterruptEnable                   phy5123_mcdSetInterruptEnable
#define mcdGetInterruptEnable                   phy5123_mcdGetInterruptEnable
#define mcdGetInterruptStatus                   phy5123_mcdGetInterruptStatus
#define mcdGetRealtimeStatus                    phy5123_mcdGetRealtimeStatus
#define mcdSetInterruptEnableEx                 phy5123_mcdSetInterruptEnableEx
#define mcdGetInterruptEnableEx                 phy5123_mcdGetInterruptEnableEx
#define mcdGetInterruptStatusEx                 phy5123_mcdGetInterruptStatusEx
#define mcdGetRealtimeStatusEx                  phy5123_mcdGetRealtimeStatusEx
/* src/mcdAPIInternal.o */
#define mcdCheckIsDeviceSupported               phy5123_mcdCheckIsDeviceSupported
#define mcdSetAutoNegParameters                 phy5123_mcdSetAutoNegParameters
#define mcdIsPortValid                          phy5123_mcdIsPortValid
#define mcdIsFecParamValid                      phy5123_mcdIsFecParamValid
#define mcdPowerMgmtLineWait                    phy5123_mcdPowerMgmtLineWait
#define mcdPCSModePortPowerUp                   phy5123_mcdPCSModePortPowerUp
#define mcdPortPowerUp                          phy5123_mcdPortPowerUp
#define mcdConfigRepeaterCK                     phy5123_mcdConfigRepeaterCK
#define mcdChannelSwReset                       phy5123_mcdChannelSwReset
#define mcdChannelMacBypass                     phy5123_mcdChannelMacBypass
#define mcdClockGatingControl                   phy5123_mcdClockGatingControl
#define mcdGlobalModeSet                        phy5123_mcdGlobalModeSet
#define mcdPortSerdesTxEnable                   phy5123_mcdPortSerdesTxEnable
#define mcdConfigurePcs1gR1                     phy5123_mcdConfigurePcs1gR1
#define mcdConfigurePcs2p5gR1                   phy5123_mcdConfigurePcs2p5gR1
#define mcdConfigurePcs2p5gBasex                phy5123_mcdConfigurePcs2p5gBasex
#define mcdConfigurePcs10gR1                    phy5123_mcdConfigurePcs10gR1
#define mcdConfigurePcs25gR1                    phy5123_mcdConfigurePcs25gR1
#define mcdConfigurePcs40g                      phy5123_mcdConfigurePcs40g
#define mcdConfigurePcs100gR4                   phy5123_mcdConfigurePcs100gR4
#define mcd25gRsFecInit                         phy5123_mcd25gRsFecInit
#define mcdOneSideSetMode                       phy5123_mcdOneSideSetMode
#define mcdSetHostSideRetimerMode               phy5123_mcdSetHostSideRetimerMode
#define mcdPortPowerHwResetTimeout              phy5123_mcdPortPowerHwResetTimeout
#define mcdPortPowerHwReset                     phy5123_mcdPortPowerHwReset
#define mcdPortModeGetLanesNum                  phy5123_mcdPortModeGetLanesNum
#define mcdGetLaneSpeed                         phy5123_mcdGetLaneSpeed
#define mcdPortGetLanesNum                      phy5123_mcdPortGetLanesNum
#define mcdGetApPortParams                      phy5123_mcdGetApPortParams
#define mcdSetMode                              phy5123_mcdSetMode
#define mcdGetModeSpeed                         phy5123_mcdGetModeSpeed
#define mcdIsPortModePcsControlled              phy5123_mcdIsPortModePcsControlled
#define mcdGetNumberPorts                       phy5123_mcdGetNumberPorts
#define mcdGetAutoNegAcquiredSpeed              phy5123_mcdGetAutoNegAcquiredSpeed
#define mcdSetAutoNegAcquiredSpeed              phy5123_mcdSetAutoNegAcquiredSpeed
#define mcdReadPCSLinkStatus                    phy5123_mcdReadPCSLinkStatus
#define mcdReadPCSLineLinkStatus                phy5123_mcdReadPCSLineLinkStatus
#define mcdDisableAllUmacInterrupts             phy5123_mcdDisableAllUmacInterrupts
#define mcdPortResetTimeout                     phy5123_mcdPortResetTimeout
#define mcdLaneSoftReset                        phy5123_mcdLaneSoftReset
#define mcdLaneResetTimeout                     phy5123_mcdLaneResetTimeout
#define mcdInitBroadcastDev                     phy5123_mcdInitBroadcastDev
#define mcdLoadCm3FWImageStartOrEnd             phy5123_mcdLoadCm3FWImageStartOrEnd
#define mcdLoadCm3FWImageLoad                   phy5123_mcdLoadCm3FWImageLoad
#define mcdServiceCpuRead                       phy5123_mcdServiceCpuRead
#define mcdServiceCpuWrite                      phy5123_mcdServiceCpuWrite
#define mcdPortPollingLinkStatusStart           phy5123_mcdPortPollingLinkStatusStart
#define mcdClearSerdesSignalLostIntCause        phy5123_mcdClearSerdesSignalLostIntCause
#define mcdGetSerdesSignalLostIntCause          phy5123_mcdGetSerdesSignalLostIntCause
#define mcdCheckSerdesSignalStability           phy5123_mcdCheckSerdesSignalStability
#define mcdReadRepeaterLinkStatus               phy5123_mcdReadRepeaterLinkStatus
#define mcdTryLockHwSemaphore                   phy5123_mcdTryLockHwSemaphore
#define mcdLockHwSemaphore                      phy5123_mcdLockHwSemaphore
#define mcdUnlockHwSemaphore                    phy5123_mcdUnlockHwSemaphore
#define mcdPowerConsumptionReduce               phy5123_mcdPowerConsumptionReduce
#define mcdGetHwTimestamp                       phy5123_mcdGetHwTimestamp
/* src/mcdDiagnostics.o */
#define mcdGetChipRevision                      phy5123_mcdGetChipRevision
#define mcdGetChipFWRevision                    phy5123_mcdGetChipFWRevision
#define mcdCheckChipCapablities                 phy5123_mcdCheckChipCapablities
#define mcdGetSerdesSignalDetectAndDspLock      phy5123_mcdGetSerdesSignalDetectAndDspLock
#define mcdSetLoopback                          phy5123_mcdSetLoopback
#define mcdSetLineLoopback                      phy5123_mcdSetLineLoopback
#define mcdSetHostLoopback                      phy5123_mcdSetHostLoopback
#define mcdConfigurePktGeneratorChecker         phy5123_mcdConfigurePktGeneratorChecker
#define mcdEnablePktGeneratorChecker            phy5123_mcdEnablePktGeneratorChecker
#define mcdPktGeneratorCounterReset             phy5123_mcdPktGeneratorCounterReset
#define mcdPktGeneratorGetCounter               phy5123_mcdPktGeneratorGetCounter
#define mcdSetLineSidePRBSPattern               phy5123_mcdSetLineSidePRBSPattern
#define mcdSetHostSidePRBSPattern               phy5123_mcdSetHostSidePRBSPattern
#define mcdSetPRBSEnableTxRx                    phy5123_mcdSetPRBSEnableTxRx
#define mcdPRBSCounterReset                     phy5123_mcdPRBSCounterReset
#define mcdSetPRBSWaitForLock                   phy5123_mcdSetPRBSWaitForLock
#define mcdGetPRBSWaitForLock                   phy5123_mcdGetPRBSWaitForLock
#define mcdSetPRBSClearOnRead                   phy5123_mcdSetPRBSClearOnRead
#define mcdGetPRBSClearOnRead                   phy5123_mcdGetPRBSClearOnRead
#define mcdGetPRBSLocked                        phy5123_mcdGetPRBSLocked
#define mcdGetPRBSCounts                        phy5123_mcdGetPRBSCounts
#define mcdSetTxPolarity                        phy5123_mcdSetTxPolarity
#define mcdGetTxPolarity                        phy5123_mcdGetTxPolarity
#define mcdSetRxPolarity                        phy5123_mcdSetRxPolarity
#define mcdGetRxPolarity                        phy5123_mcdGetRxPolarity
#define mcdSetTxFFE                             phy5123_mcdSetTxFFE
#define mcdGetTxFFE                             phy5123_mcdGetTxFFE
/* mcd/src/mcdFwDownload.o */
#define mcdLoadBroadcastDropDevShadow              phy5123_mcdLoadBroadcastDropDevShadow
#define mcdLoadSBusSerdesFW                        phy5123_mcdLoadSBusSerdesFW
#define mcdLoadSBusMasterFW                        phy5123_mcdLoadSBusMasterFW
#define mcdLoadZ80FWImage                          phy5123_mcdLoadZ80FWImage
#define mcdLoadCm3FWImage                          phy5123_mcdLoadCm3FWImage
#define mcdIndirectSBusFwImageWrite                phy5123_mcdIndirectSBusFwImageWrite
#define mcdLoadROMImageToRAM                       phy5123_mcdLoadROMImageToRAM
#define mcdLoadEEPROMImageToRAM                    phy5123_mcdLoadEEPROMImageToRAM
#define mcdUpdateEEPROMImage                       phy5123_mcdUpdateEEPROMImage
#define mcdLoadSBusSerdesFromCpuMemoryAllDevices   phy5123_mcdLoadSBusSerdesFromCpuMemoryAllDevices
#define mcdLoadSBusMasterFromCpuMemoryAllDevices   phy5123_mcdLoadSBusMasterFromCpuMemoryAllDevices
#define mcdLoadCm3FWImageAllDevices                phy5123_mcdLoadCm3FWImageAllDevices
/* src/mcdHwCntl.o */
#define mcdHwXmdioWrite                         phy5123_mcdHwXmdioWrite
#define mcdHwXmdioRead                          phy5123_mcdHwXmdioRead
#define mcdHwGetPhyRegField                     phy5123_mcdHwGetPhyRegField
#define mcdHwSetPhyRegField                     phy5123_mcdHwSetPhyRegField
#define mcdHwGetRegFieldFromWord                phy5123_mcdHwGetRegFieldFromWord
#define mcdHwSetRegFieldToWord                  phy5123_mcdHwSetRegFieldToWord
#define mcdWait                                 phy5123_mcdWait
#define mcdHwXmdioWaitStatus                    phy5123_mcdHwXmdioWaitStatus
#define mcdHwXmdioWait32bitWrite                phy5123_mcdHwXmdioWait32bitWrite
#define mcdHwXmdioWait32bitRead                 phy5123_mcdHwXmdioWait32bitRead
#define prvMcdPhyShadowRegCheckAndSet           phy5123_prvMcdPhyShadowRegCheckAndSet
#define prvMcdPhyShadowRegInvalidate            phy5123_prvMcdPhyShadowRegInvalidate
#define prvMcdPhyShadowWrite16BitRegister       phy5123_prvMcdPhyShadowWrite16BitRegister
#define prvMcdIs32bitAddressExternal            phy5123_prvMcdIs32bitAddressExternal
#define prvMcd32bitAddressExternalFixed         phy5123_prvMcd32bitAddressExternalFixed
#define mcdHwXmdioWrite32bit                    phy5123_mcdHwXmdioWrite32bit
#define mcdHwXmdioAccessInit32bit               phy5123_mcdHwXmdioAccessInit32bit
#define mcdHwXmdioRead32bit                     phy5123_mcdHwXmdioRead32bit
#define mcdHwSetPhyRegField32bit                phy5123_mcdHwSetPhyRegField32bit
#define mcdHwGetPhyRegField32bit                phy5123_mcdHwGetPhyRegField32bit
#define mcdHwSetPhyRegMask32bit                 phy5123_mcdHwSetPhyRegMask32bit
#define mcdHwGetPhyRegMask32bit                 phy5123_mcdHwGetPhyRegMask32bit
#define mcdHwXmdioWaitStatus32Bit               phy5123_mcdHwXmdioWaitStatus32Bit
/* src/mcdHwSerdesCntl.o */
#define mcdSerdesSetRetimerRequireSignalOk           phy5123_mcdSerdesSetRetimerRequireSignalOk
#define mcdLoadSBusSerdesFromCpuMemory               phy5123_mcdLoadSBusSerdesFromCpuMemory
#define mcdLoadSBusMasterFromCpuMemory               phy5123_mcdLoadSBusMasterFromCpuMemory
#define mcdSetSetSerdesElectricalParametersDB        phy5123_mcdSetSetSerdesElectricalParametersDB
#define mcdSetSetSerdesDefaultElectricalParameters   phy5123_mcdSetSetSerdesDefaultElectricalParameters
#define mcdSerdesResetImpl                           phy5123_mcdSerdesResetImpl
#define mcdSerdesGetTemperature                      phy5123_mcdSerdesGetTemperature
#define mcdSerdesShiftCalc                           phy5123_mcdSerdesShiftCalc
#define mcdSerdesSignalDetectGet                     phy5123_mcdSerdesSignalDetectGet
#define mcdSerdesRxSignalCheck                       phy5123_mcdSerdesRxSignalCheck
#define mcdSerdesTxAutoTuneStatusShort               phy5123_mcdSerdesTxAutoTuneStatusShort
#define mcdSerdesEyeGetExt                           phy5123_mcdSerdesEyeGetExt
#define mcdSerdesGetEye                              phy5123_mcdSerdesGetEye
#define mcdSerdesSetTxPolarity                       phy5123_mcdSerdesSetTxPolarity
#define mcdSerdesSetRxPolarity                       phy5123_mcdSerdesSetRxPolarity
#define mcdSerdesAccessValidate                      phy5123_mcdSerdesAccessValidate
#define mcdInitSerdesDev                             phy5123_mcdInitSerdesDev
#define mcdCheckSerdesInitStatus                     phy5123_mcdCheckSerdesInitStatus
#define mcdSerdesAccessLock                          phy5123_mcdSerdesAccessLock
#define mcdSerdesAccessUnlock                        phy5123_mcdSerdesAccessUnlock
#define mcdSerdesSbmVoltageGet                       phy5123_mcdSerdesSbmVoltageGet
#define mcdSerdesGetRxPolarity                       phy5123_mcdSerdesGetRxPolarity
#define mcdSerdesGetTxPolarity                       phy5123_mcdSerdesGetTxPolarity
#define mcdSerdesPolarityConfigGetImpl               phy5123_mcdSerdesPolarityConfigGetImpl
#define mcdSerdesPolarityConfigImpl                  phy5123_mcdSerdesPolarityConfigImpl
#define mcdSerdesSignalOkThresholdGet                phy5123_mcdSerdesSignalOkThresholdGet
#define mcdSerdesSignalOkCfg                         phy5123_mcdSerdesSignalOkCfg
#define mcdSerdesTxAutoTuneStop                      phy5123_mcdSerdesTxAutoTuneStop
#define mcdSerdesDfeConfig_noSignalCheck             phy5123_mcdSerdesDfeConfig_noSignalCheck
#define mcdSerdesDfeConfig                           phy5123_mcdSerdesDfeConfig
#define mcdSerdesTxEnableGet                         phy5123_mcdSerdesTxEnableGet
#define mcdSerdesTxEnable                            phy5123_mcdSerdesTxEnable
#define mcdSerdesSpicoInterrupt                      phy5123_mcdSerdesSpicoInterrupt
#define mcdSerdesAutoTuneStatus                      phy5123_mcdSerdesAutoTuneStatus
#define mcdSerdesAutoTuneStatusShort                 phy5123_mcdSerdesAutoTuneStatusShort
#define mcdSerdesArrayAutoTuneSet                    phy5123_mcdSerdesArrayAutoTuneSet
#define mcdSerdesShiftSamplePoint                    phy5123_mcdSerdesShiftSamplePoint
#define mcdSerdesManualCtleConfig                    phy5123_mcdSerdesManualCtleConfig
#define mcdSerdesManualTxConfig                      phy5123_mcdSerdesManualTxConfig
#define mcdSerdesCalCodeGet                          phy5123_mcdSerdesCalCodeGet
#define mcdSerdesCalCodeSet                          phy5123_mcdSerdesCalCodeSet
#define mcdSerdesCalCodeShift                        phy5123_mcdSerdesCalCodeShift
#define mcdSerdesVcoConfig                           phy5123_mcdSerdesVcoConfig
#define mcdSerdesSetRetimerClockLaneSteeringMode     phy5123_mcdSerdesSetRetimerClockLaneSteeringMode
#define mcdSerdesSetRetimerClock                     phy5123_mcdSerdesSetRetimerClock
#define mcdSerdesSetApRetimerMode                    phy5123_mcdSerdesSetApRetimerMode
#define mcdSerdesEnhanceTune                         phy5123_mcdSerdesEnhanceTune
#define mcdSerdesSetRetimerMode                      phy5123_mcdSerdesSetRetimerMode
#define mcdSerdesAutoTuneStartExtAp                  phy5123_mcdSerdesAutoTuneStartExtAp
#define mcdSerdesAutoTuneStartExt                    phy5123_mcdSerdesAutoTuneStartExt
#define mcdSerdesRxTune                              phy5123_mcdSerdesRxTune
#define mcdSerdesSetOneSideRetimerMode               phy5123_mcdSerdesSetOneSideRetimerMode
#define mcdSerdesTxAutoTuneStart                     phy5123_mcdSerdesTxAutoTuneStart
#define mcdSerdesRxAutoTuneStart                     phy5123_mcdSerdesRxAutoTuneStart
#define mcdSerdesAutoTuneStart                       phy5123_mcdSerdesAutoTuneStart
#define mcdSerdesAutoTuneResult                      phy5123_mcdSerdesAutoTuneResult
#define mcdSerdesManualCtleConfigGet                 phy5123_mcdSerdesManualCtleConfigGet
#define mcdSerdesManualTxConfigGet                   phy5123_mcdSerdesManualTxConfigGet
#define mcdLaneSteeringOtherSideCfg					 phy5123_mcdLaneSteeringOtherSideCfg
#define mcdLaneSteeringAutoTuneStart				 phy5123_mcdLaneSteeringAutoTuneStart
#define mcdSerdesRetimerSpecialPowerUp               phy5123_mcdSerdesRetimerSpecialPowerUp
#define mcdSerdesPowerCtrl                           phy5123_mcdSerdesPowerCtrl
#define mcdSetSerdesLaneCfgForRetimerMode            phy5123_mcdSetSerdesLaneCfgForRetimerMode
#define mcdSetApRetimerMode                          phy5123_mcdSetApRetimerMode
#define mcdSetRetimerMode                            phy5123_mcdSetRetimerMode
#define mcdExecuteIndirectSBusCmd                    phy5123_mcdExecuteIndirectSBusCmd
#define mcdIndirectSBusWrite                         phy5123_mcdIndirectSBusWrite
#define mcdIndirectSBusRead                          phy5123_mcdIndirectSBusRead
#define mcdSerdesInterrupt                           phy5123_mcdSerdesInterrupt
#define mcdSbusInterrupt                             phy5123_mcdSbusInterrupt
#define mcdFreeSerdesDev                             phy5123_mcdFreeSerdesDev
#define mcdSerdesGetRevision                         phy5123_mcdSerdesGetRevision
#define mcdSerdesGetVoltage                          phy5123_mcdSerdesGetVoltage
#define mcdSerdesGetTxFFE                            phy5123_mcdSerdesGetTxFFE
#define mcdSerdesSetTxFFE                            phy5123_mcdSerdesSetTxFFE
#define mcdSerdesGetCDRLock                          phy5123_mcdSerdesGetCDRLock
#define mcdSerdesPMDTrainingLog                      phy5123_mcdSerdesPMDTrainingLog
#define mcdSerdesTxInjectError                       phy5123_mcdSerdesTxInjectError
#define mcdSerdesRxInjectError                       phy5123_mcdSerdesRxInjectError
#define mcdSerdesSetTxPRBS                           phy5123_mcdSerdesSetTxPRBS
#define mcdSerdesGetTxPRBS                           phy5123_mcdSerdesGetTxPRBS
#define mcdSerdesSetTxUserData                       phy5123_mcdSerdesSetTxUserData
#define mcdSerdesGetTxUserData                       phy5123_mcdSerdesGetTxUserData
#define mcdSerdesSetRxCmpData                        phy5123_mcdSerdesSetRxCmpData
#define mcdSerdesGetRxCmpData                        phy5123_mcdSerdesGetRxCmpData
#define mcdSerdesGetErrCount                         phy5123_mcdSerdesGetErrCount
#define mcdSerdesGetLoopbackInfo                     phy5123_mcdSerdesGetLoopbackInfo
#define mcdSerdesSetLoopback                         phy5123_mcdSerdesSetLoopback
#define mcdSerdesReset                               phy5123_mcdSerdesReset
#define mcdSerdesDigitalReset                        phy5123_mcdSerdesDigitalReset
#define mcdSerdesTestGen                             phy5123_mcdSerdesTestGen
#define mcdSerdesTestGenGet                          phy5123_mcdSerdesTestGenGet
#define mcdSerdesTestGenStatus                       phy5123_mcdSerdesTestGenStatus
#define mcdPrbsStartCheck                            phy5123_mcdPrbsStartCheck
#define mcdSerdesClockRegular                        phy5123_mcdSerdesClockRegular
/* src/mcdInitialization.o */
#define mcdInitDriver                                phy5123_mcdInitDriver
#define mcdUnloadDriver                              phy5123_mcdUnloadDriver
#define mcdInitDriverAllDevices                      phy5123_mcdInitDriverAllDevices
#define mcdLedControl                                phy5123_mcdLedControl
#define mcdPortReset                                 phy5123_mcdPortReset
#define mcdChipAndZ80ResetControl                    phy5123_mcdChipAndZ80ResetControl
/* src/mcdInternalSerdesFwLoad.o */
#define mcd_copy_aapl_ip_types_db                    phy5123_mcd_copy_aapl_ip_types_db
#define mcd_avago_spico_upload_reset                 phy5123_mcd_avago_spico_upload_reset
#define mcd_avago_spico_upload_check_crc             phy5123_mcd_avago_spico_upload_check_crc
#define mcd_avago_spico_upload                       phy5123_mcd_avago_spico_upload
#define mcd_avago_spico_upload_swap_image_start      phy5123_mcd_avago_spico_upload_swap_image_start
#define mcd_avago_spico_upload_swap_image_check_crc  phy5123_mcd_avago_spico_upload_swap_image_check_crc
#define mcd_avago_spico_upload_swap_image_load       phy5123_mcd_avago_spico_upload_swap_image_load
#define mcd_avago_spico_upload_swap_image            phy5123_mcd_avago_spico_upload_swap_image
#define mcd_avago_spico_upload_broacast              phy5123_mcd_avago_spico_upload_broacast
#define mcd_avago_spico_upload_swap_image_broadcast  phy5123_mcd_avago_spico_upload_swap_image_broadcast
/* src/mcdRsFEC.o */
#define mcdSetRsFecControl                      phy5123_mcdSetRsFecControl
#define mcdGetRsFecStatus                       phy5123_mcdGetRsFecStatus
#define mcdGetRsFecPCSAlignmentStatus           phy5123_mcdGetRsFecPCSAlignmentStatus
#define mcdGetRsFecPMALaneMapping               phy5123_mcdGetRsFecPMALaneMapping
#define mcdGetRsFecPCSLaneMapping               phy5123_mcdGetRsFecPCSLaneMapping
#define mcdGetRsFecCorrectedCwCntr              phy5123_mcdGetRsFecCorrectedCwCntr
#define mcdGetRsFecUnCorrectedCwCntr            phy5123_mcdGetRsFecUnCorrectedCwCntr
#define mcdGetRsFecSymbolErrorCntr              phy5123_mcdGetRsFecSymbolErrorCntr
#define mcdGetRsFecBipErrorCntr                 phy5123_mcdGetRsFecBipErrorCntr
/* src/mcdUtils.o */
#define mcdDbgPrint                             phy5123_mcdDbgPrint
#define mcdMemSet                               phy5123_mcdMemSet
#define mcdMemCpy                               phy5123_mcdMemCpy
#define mcdMemCmp                               phy5123_mcdMemCmp
#define mcdStrlen                               phy5123_mcdStrlen
/* src/mcdInternalIpcApis.o */
#define mcdInternalServiceCpuMsgSend            phy5123_mcdInternalServiceCpuMsgSend
#define mcdInternalServiceCpuMsgRecv            phy5123_mcdInternalServiceCpuMsgRecv
#define mcdInternalIpcDbInit                    phy5123_mcdInternalIpcDbInit
#define mcdInternalGetQueueId                   phy5123_mcdInternalGetQueueId
#define mcdInternalReturnQueueId                phy5123_mcdInternalReturnQueueId
#define mcdInternalIpcCtrlMsgTx                 phy5123_mcdInternalIpcCtrlMsgTx
#define mcdInternalSetIpcInfo                   phy5123_mcdInternalSetIpcInfo
#define mcdInternalIpcReplyMsgRx                phy5123_mcdInternalIpcReplyMsgRx
#define mcdInternalIpcSendRequestAndGetReply    phy5123_mcdInternalIpcSendRequestAndGetReply
#define mcdInternalPortApStartIpc               phy5123_mcdInternalPortApStartIpc
#define mcdInternalPortApStopIpc                phy5123_mcdInternalPortApStopIpc
#define mcdSerdesCfgAddrGetIpc                  phy5123_mcdSerdesCfgAddrGetIpc
#define mcdSerdesAaplInitIpc                    phy5123_mcdSerdesAaplInitIpc
#define mcdSetSquelchRxClockControlIpc          phy5123_mcdSetSquelchRxClockControlIpc
#define mcdPortApStatsGetIpc                    phy5123_mcdPortApStatsGetIpc
#define mcdPortApDebugGetIpc                    phy5123_mcdPortApDebugGetIpc
#define mcdApPortCtrlDebugGet                   phy5123_mcdApPortCtrlDebugGet
#define mcdServiceCpuFwPostInit                 phy5123_mcdServiceCpuFwPostInit
#define mcdAutoNegPortCtrlStart                 phy5123_mcdAutoNegPortCtrlStart
#define mcdAutoNegPortCtrlStop                  phy5123_mcdAutoNegPortCtrlStop
#define mcdInternalPortApStatusGetIpc           phy5123_mcdInternalPortApStatusGetIpc
#define mcdPortApIntropGetIpc                   phy5123_mcdPortApIntropGetIpc
#define mcdApPortCtrlStatusGet                  phy5123_mcdApPortCtrlStatusGet
#define mcdApPortCtrlStatsGet                   phy5123_mcdApPortCtrlStatsGet
#define mcdApPortCtrlIntropGet                  phy5123_mcdApPortCtrlIntropGet
#define mcdPortPollingLinkStatusStartIpc        phy5123_mcdPortPollingLinkStatusStartIpc
#define mcdPortPollingLinkStatusStopIpc         phy5123_mcdPortPollingLinkStatusStopIpc
/* src/mcdInternalShmIpc.o */
#define mcdInternalShmIpcTraceEnableSet      phy5123_mcdInternalShmIpcTraceEnableSet
#define mcdInternalShmIpcInit                phy5123_mcdInternalShmIpcInit
#define mcdInternalShmIpcConfigChannel       phy5123_mcdInternalShmIpcConfigChannel
#define mcdInternalShmIpcSend                phy5123_mcdInternalShmIpcSend
#define mcdInternalShmIpcRecv                phy5123_mcdInternalShmIpcRecv
#define mcdInternalShmIpcRxReady             phy5123_mcdInternalShmIpcRxReady
#define mcdInternalShmIpcRxChnReady          phy5123_mcdInternalShmIpcRxChnReady
#define mcdInternalShmIpcRegRead             phy5123_mcdInternalShmIpcRegRead
#define mcdInternalShmIpcRegWrite            phy5123_mcdInternalShmIpcRegWrite
/* src/mcdPortApCtrlLog.o */
#define mcdApPortCtrlDebugParamsSet          phy5123_mcdApPortCtrlDebugParamsSet
#define mcdLogParamsSet                      phy5123_mcdLogParamsSet
#define mcdApConvertHdc2Vec                  phy5123_mcdApConvertHdc2Vec
#define mcdApConvertPortMode                 phy5123_mcdApConvertPortMode
#define mcdArbSmStateDesc                    phy5123_mcdArbSmStateDesc
#define mcdApPortCtrlStatusShow              phy5123_mcdApPortCtrlStatusShow
#define mcdApPortCtrlStatsShow               phy5123_mcdApPortCtrlStatsShow
#define mcdApPortCtrlIntropShow              phy5123_mcdApPortCtrlIntropShow
#define mcdLogInfoShow                       phy5123_mcdLogInfoShow
#define mcdPollingStatShow                   phy5123_mcdPollingStatShow
#define mcdApPortCtrlDebugInfoShowEntry      phy5123_mcdApPortCtrlDebugInfoShowEntry
#define mcdApPortCtrlDebugInfoShow           phy5123_mcdApPortCtrlDebugInfoShow
/* src/mcdAPIInternal.o */
#define portModeTbl                          phy5123_portModeTbl
/* src/mcdHwSerdesCntl.o */
#define serdesElectricalParams               phy5123_serdesElectricalParams
#define mcdSerdesTxRxTuneParamsArray         phy5123_mcdSerdesTxRxTuneParamsArray
/* src/mcdUtils.o */
#define mcd_debug_level                      phy5123_mcd_debug_level
/* src/mcdPortApCtrlLog.o */
#define mcdApPortMngSmState                  phy5123_mcdApPortMngSmState
#define mcdApPortMngSmStatus                 phy5123_mcdApPortMngSmStatus
/* src/mcdInternalShmIpc.o */
#define mcdInternalShmIpcTraceEnable         phy5123_mcdInternalShmIpcTraceEnable

#if C_LINKAGE
#if defined __cplusplus
}
#endif
#endif

#endif /* MCD_API_HIDDEN_NAMES_H */


